[package]
name = "nmea2k"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitfield = "0.14.0"
nom = "7.1.3"
num-derive = "0.4.0"

[dependencies.num-traits]
version = "0.2"
default-features = false
